#  Лабораторна робота "Обробка табличних даних засобами бібліотеки Pandas"

__Метою__ лабораторної роботи є вивчення технологій первинного аналізу даних в середовищі бібліотеки Pandas, а саме здобуття навичок:
- працювати з даними використовуючи мову Python та пакет Pandas
- робити передобробку даних
- знаходити прості закономірності у даних

In [1]:
# підключити бібліотеки Pandas та NumPy
import pandas as pd
import numpy as np

## 1. Створення  DataFrame

__DataFrame__ — це двовимірна неоднорідна таблична структура даних із змінюваними розмірами з іменованими вісями (рядками та стовпцями)

### ПРИКЛАДИ

In [2]:
# створити DataFrame з 1 колонкою з python-списка
df = pd.DataFrame(["Петя", "Вася", "Микола"])
print(df)
print(type(df))

        0
0    Петя
1    Вася
2  Микола
<class 'pandas.core.frame.DataFrame'>


In [3]:
# створити DataFrame з np-матриці розміром 10х10 випадкових чисел
mat = np.random.randint(100, 500, (10,10), dtype="int16")
print(mat)
df = pd.DataFrame(mat)
df

[[204 223 463 342 241 486 215 368 277 378]
 [391 364 284 291 226 193 117 126 161 196]
 [189 260 458 483 317 339 396 408 390 434]
 [461 298 298 151 134 257 336 380 268 292]
 [344 357 137 255 336 208 197 146 171 343]
 [186 417 159 452 210 123 423 244 364 116]
 [149 269 273 186 396 429 383 344 368 386]
 [402 263 200 421 161 327 453 329 387 143]
 [279 306 219 162 388 256 204 305 218 341]
 [128 238 180 132 249 372 326 394 324 375]]


0    1    2    3    4    5    6    7    8    9
0  204  223  463  342  241  486  215  368  277  378
1  391  364  284  291  226  193  117  126  161  196
2  189  260  458  483  317  339  396  408  390  434
3  461  298  298  151  134  257  336  380  268  292
4  344  357  137  255  336  208  197  146  171  343
5  186  417  159  452  210  123  423  244  364  116
6  149  269  273  186  396  429  383  344  368  386
7  402  263  200  421  161  327  453  329  387  143
8  279  306  219  162  388  256  204  305  218  341
9  128  238  180  132  249  372  326  394  324  375

In [4]:
# створити DataFrame з 2-мірного випадкового масиву з іменованими колонками
arr = np.random.random((5,3))
print(arr)
df = pd.DataFrame(arr, columns=["колонка 1", "колонка 2", "колонка 3"])
df

[[0.41683399 0.13917494 0.76948558]
 [0.63518377 0.6135846  0.3099559 ]
 [0.34482873 0.06383885 0.58437408]
 [0.96060921 0.35020087 0.9456875 ]
 [0.76688758 0.91951792 0.03138117]]


колонка 1  колонка 2  колонка 3
0   0.416834   0.139175   0.769486
1   0.635184   0.613585   0.309956
2   0.344829   0.063839   0.584374
3   0.960609   0.350201   0.945687
4   0.766888   0.919518   0.031381

In [5]:
# створити DataFrame з python-словника в якому ключ - це ім'я, а значення - 
# це масив з 5-ти випадкових чисел з модифікованими індексами рядків
d = {"Петя": np.random.random(5),
    "Вася" : np.random.random(5),
    "Микола":np.random.random(5)
    }
pd.DataFrame(d, index=[10,20,30,40,50])

Петя      Вася    Микола
10  0.857974  0.606890  0.602383
20  0.367546  0.101020  0.154891
30  0.488476  0.307656  0.095100
40  0.622589  0.648679  0.506010
50  0.035535  0.800429  0.874668

In [6]:
# створити dataFrame з ітеруємого об'єкта
name = ["Вася", "Петя", "Микола"]
rik = [2001, 2000, 2003]
name_rik = list(zip(name, rik))
print(name_rik)
df = pd.DataFrame(name_rik, columns=["Ім'я", "Рік народження"])
df

[('Вася', 2001), ('Петя', 2000), ('Микола', 2003)]


Ім'я  Рік народження
0    Вася            2001
1    Петя            2000
2  Микола            2003

In [7]:
str(name_rik[0])

"('Вася', 2001)"

In [10]:
!echo "Вася, 2001\nПетя, 2000,\nМикола,2003\n" > file.csv
!cat file.csv
# створити DataFrame з csv-файлу
df = pd.read_csv("file.csv", names=["Ім'я", "Рік народження"])
df

<class 'AttributeError'>: module 'pexpect' has no attribute 'TIMEOUT'

### ЗАВДАННЯ

In [18]:
# ЗАВДАННЯ 1.1: створити датафрейм з списку 10-ти простих чисел
df1_1 = pd.DataFrame(['2','3','5','7','11','13','17','19','23','29'])
df1_1

0
0   2
1   3
2   5
3   7
4  11
5  13
6  17
7  19
8  23
9  29

In [25]:
# ЗАВДАННЯ 1.2: створити датафрейм з матриці 5х6 чисел з плаваючою точкою
arr1_2= np.random.rand(5, 6)
df1_2 = pd.DataFrame(arr1_2)
df1_2

0         1         2         3         4         5
0  0.026615  0.997578  0.585155  0.880178  0.282673  0.758598
1  0.935645  0.131694  0.896420  0.892982  0.831537  0.161692
2  0.940845  0.569077  0.812939  0.529638  0.732961  0.592804
3  0.950749  0.206354  0.328766  0.389391  0.488669  0.965150
4  0.950512  0.097435  0.920441  0.629022  0.055984  0.561254

In [26]:
name = ["Петро", "Іван", "Степан"]
secondname = ["Петров", "Іванов", "Степанов"]
year = ["2000", "2002", "2001"]
number = ["222-222-2222", "333-333-3333", "444-444-4444"]
spisok = list(zip(name, secondname, year, number))
df1_3 = pd.DataFrame(spisok, columns=["Ім'я", "прізвище", "Рік народження", "телефон"])
df1_3

Ім'я  прізвище Рік народження       телефон
0   Петро    Петров           2000  222-222-2222
1    Іван    Іванов           2002  333-333-3333
2  Степан  Степанов           2001  444-444-4444

In [38]:
# ЗАВДАННЯ 1.4: створити датафрейм з 20 перших рядків excel-файлу, 
# який розташовано за адресою: 
# https://file-examples-com.github.io/uploads/2017/02/file_example_XLS_100.xls

df1_4= pd.read_excel("https://file-examples-com.github.io/uploads/2017/02/file_example_XLS_100.xls", nrows=20)
df1_4 

<class 'urllib.error.URLError'>: <urlopen error unknown url type: https>

## 2. Інспектування DataFrame

__Інспектування__ - це процедури вивчення внутрішньої структури даних та вмісту датафрейма

### ПРИКЛАДИ

In [39]:
# завантаження датасету `titanic` (https://ansmirnov.ru/kaggle-titanic-dataset/)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url) #ПОМИЛКА

<class 'urllib.error.URLError'>: <urlopen error unknown url type: https>

In [40]:
# отримати загальну інформацію про датасет
titanic.info()

<class 'NameError'>: name 'titanic' is not defined

In [41]:
# вивести перші 3 рядкі
titanic.head(3)

<class 'NameError'>: name 'titanic' is not defined

In [42]:
# вивести останні 2 рядки
titanic.tail(2)

<class 'NameError'>: name 'titanic' is not defined

In [43]:
# отримати імена колонок
col_names = titanic.columns
print(col_names)

<class 'NameError'>: name 'titanic' is not defined

In [44]:
# вивести загальну статистику датасету - числові поля
titanic.describe()

<class 'NameError'>: name 'titanic' is not defined

In [45]:
# вивести статитсику текстового поля `Sex` 
titanic['Sex'].describe()

<class 'NameError'>: name 'titanic' is not defined

In [46]:
# перевірити тип колонки датасету
type(titanic['Age'])

<class 'NameError'>: name 'titanic' is not defined

In [47]:
# вивести перші 10 рядків деяких колонок
cols = ["Name", "Age", "Sex"]
titanic[cols].head(10)

<class 'NameError'>: name 'titanic' is not defined

In [48]:
# вивести рядки з 100 по 110
titanic[100:110]

<class 'NameError'>: name 'titanic' is not defined

In [49]:
# вивести тільки чоловіків
cond = titanic["Sex"] == "male"
titanic[cond]

<class 'NameError'>: name 'titanic' is not defined

In [50]:
# вивести рядки в яких пропущено значення поля `Age`
cond = titanic['Age'].isna()
titanic[cond].head(3)

<class 'NameError'>: name 'titanic' is not defined

In [51]:
# вивести рядки з пасажирами вік яких з 30 до 50 років
cond = titanic['Age'].between(30, 50)
titanic[cond]

<class 'NameError'>: name 'titanic' is not defined

### ЗАВДАННЯ

In [ ]:
# ЗАВДАННЯ 2.1: вивести характеристики датасету `titanic`
...

In [ ]:
# ЗАВДАННЯ 2.2: вивести статистичні параметри полів `Age` та `Fare` датасету `titanic`
...

In [ ]:
# ЗАВДАННЯ 2.3: пірахувати кількість записів в яких заповнені усі показчики
...

In [ ]:
# ЗАВДАННЯ 2.4: пірахувати кількість виживших (survived=1) пасажирів жиночої статі (Sex=`female`)
...

## 3. Перетворення датафреймів

__Перетворення__ - це сукупність операцій та методів для зміни структури та вмісту датафрейму та окремих його елементів

### ПРИКЛАДИ

In [52]:
d = {
    "ім'я"    : ["Петя", "Вася", "Галя"],
    "вік"     : [22, 200 , 21],
    "рейтинг" : ["10", "3", "2"]
}

df = pd.DataFrame(d)
df

ім'я  вік рейтинг
0  Петя   22      10
1  Вася  200       3
2  Галя   21       2

In [53]:
# типи колонок та елементів в колонці
print(df["рейтинг"].dtype)
print(type(df['рейтинг']))

object
<class 'pandas.core.series.Series'>


In [ ]:
# Перетворити тип колонки (показчика) 'рейтинг' в ціле числове
df['рейтинг'] = df['рейтинг'].astype("int8")
print(df["рейтинг"].dtype)

In [ ]:
# додати колонку "адреса"
df["адреса"] = ["Київ", "Бровари", "Фастів"]
df

In [ ]:
#  збільшити значення "рейтинг" на 3
df['рейтинг'] = df['рейтинг'] + 3
df

In [ ]:
df

In [ ]:
# виправити значення параметру 'вік' для імені 'Вася'
df.loc[1, "вік"] = 20
df

In [ ]:
# видалити колонку `вік'
df.drop(columns='вік', inplace=True)
df

In [ ]:
# вивести 5 перших рядків датафрейму
titanic.head(5)

In [ ]:
# вивести 3 випадкових рядки датафрейму
titanic.sample(3)

In [ ]:
# відсортувати dataframe `titanic` за віком пасажиров
titanic.sort_values('Age')

In [ ]:
# перейменувати значення в `Embarked` стовпчику:
# С - Cherbourg
# Q - Queenstown
# S - Southampton
titanic['Embarked'].replace({"C": "Cherbourg", "Q": "Queenstown", "S": "Southampton"},
                           inplace=True)
titanic

In [ ]:
# підрахувати кількість пасажирів 1-го класу (Pclass=1)
cond = titanic['Pclass'] == 1
kol_pass = titanic[cond]['PassengerId'].count()
kol_pass

In [ ]:
# замінити відсутні номери кают на ''
titanic.fillna({"Cabin": "***"}, inplace=True)
titanic.head(3)

In [ ]:
# видалити рядки в яких є відсутні значення 
titanic.dropna(axis=0, how='any', inplace=True)
titanic.shape

### ЗАВДАННЯ

In [ ]:
# ЗАВДАННЯ 3.1: створити датафрейм з словника d
d = {
    "ім'я"    : ["Петя", "Вася", "Галя"],
    "вік"     : [22, 200 , 21],
    "рейтинг" : ["10", "3", "2"]
}
df = ...

In [ ]:
# ЗАВДАННЯ 3.2: додати до `df` стовбчик з показчиком 
# `рік завершення школи` = [2018, 2020, 200]
...
print(df)

In [ ]:
# ЗАВДАННЯ 3.3: виправити 'рік завершення школи' з 200 на 2020
...
print(df)

In [ ]:
# завантаження датасету `titanic` (https://ansmirnov.ru/kaggle-titanic-dataset/)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)

In [ ]:
# ЗАВДАННЯ 3.4: вивести з датасету `titanic` останні 10 записів 
...

In [ ]:
# ЗАВДАННЯ 3.5: вибрати з датасету `titanic` рядки з пасажирами чоловічої статі віком 
# від 20 до 30 років, які подорожували 2 класом
...

In [ ]:
# ЗАВДАННЯ 3.6: видалити з датасету `titanic` рядки з пасажирами у яких відсутня
# вартість (fare) квітка
df = ...
df

In [ ]:
# ЗАВДАННЯ 3.7: підрахувати середню вартість квитка у каютах 1-го класу
avg_price = ...
print(avg_price)

## 4. Агрегація датафреймів

__Агрегація__ - це функції отримання агрегованих даних шляхом групування об'єктів датафрейма 

### ПРИКЛАДИ

In [ ]:
titanic.head(3)

In [ ]:
# підрахувати середній вік пасажирів по класам кают
group_by_class = titanic.groupby(["Pclass"])
avg_age = group_by_class["Age"].mean()
print(avg_age)

In [ ]:
# підрахувати кількість чоловіків та жінок по класам кают
man_woman_count = titanic.groupby(["Pclass", "Sex"])["Sex"].count()
man_woman_count

In [ ]:
# створити таблицю в якій підраховано середню вартість білетів (Fare) в залежності
# від місця посадки (Embarked) по класам кают
tickets_cost = titanic.pivot_table(values="Fare", index="Pclass", columns="Embarked",
                   aggfunc=np.mean)
tickets_cost

### ЗАВДАННЯ

In [ ]:
# ЗАВДАННЯ 4.1: отримати відомості про максимальний вік жінок та чоловіків
max_age = ...
print(max_age)

___ЗАВДАННЯ 4.2___

на основі даних з `titanic` побудувати таблицю наступного вигляду:

Pclass  |Male  | Female
--------|------|-------
1  | ... | ...
2  | ... | ...
3  | ... | ...

де замість `...` повинно бути кількість виживших (Survived) чоловіків та жінок відповідно

In [ ]:
surv_table = ...
surv_table